; common settings
EnableNews=false
Login=31383734
Server=ICMarketsSC-Demo03

; experts settings
ExpertsEnable=true
ExpertsDllImport=true
ExpertsExpImport=true
ExpertsTrades=false

; start strategy tester
TestExpert=Moving Average
TestExpertParameters=
TestSymbol=EURUSD
TestPeriod=H1
TestModel=2
TestOptimization=false
TestDateEnable=true
TestFromDate=2025.01.01
TestToDate=2025.01.15
TestVisualEnable=false
TestReplaceReport=true
TestReport=tester\files\smoke_moving_average_portable
TestShutdownTerminal=true
