[Default]
FKey_OutlookBarIndex=1
CCL_OutlookBarIndex=3
MMC_RibbonBarIndex=5
;RibbonBarIndex=1
OutlookBarIndex=1

GPPadCode=GPMM
XYPadCode=GPMMXY

F1_PadCode=GPMM|#买入
F2_PadCode=GPMM|#卖出


[Panel]
JyPanelNum=3

Name1=买入
Type1=TC
FeatureID1=flatjy.ptbuy
ParamStr1=

Name2=卖出
Type2=TC
FeatureID2=flatjy.ptsell
ParamStr2=

Name3=快捷买卖
Type3=TC
FeatureID3=flatjy.kswt
ParamStr3=

[Panel_OT]
JyPanelNum=1
Name1=查询
Type1=JYZDDATA
FeatureID1=gg_jycx

[Panel_XY]
JyPanelNum=5

Name1=买入
Type1=TC
FeatureID1=flatjy.ptbuy
ParamStr1=

Name2=卖出
Type2=TC
FeatureID2=flatjy.ptsell
ParamStr2=

Name3=快捷买卖
Type3=TC
FeatureID3=flatjy.kswt
ParamStr3=

Name4=融买
Type4=TC
FeatureID4=flatjy.rzbuy
ParamStr4=

Name5=融卖
Type5=TC
FeatureID5=flatjy.rqsell
ParamStr5=

[Panel_XY_OT]
JyPanelNum=1

Name1=查询
Type1=JYZDDATA
FeatureID1=gg_jycx

[Panel_Multi]
JyPanelNum=5

Name1=多户买入
Type1=CLOUDDIY
FeatureID1=256
ParamStr1=

Name2=多户卖出
Type2=CLOUDDIY
FeatureID2=257
ParamStr2=

Name3=融资买入
Type3=CLOUDDIY
FeatureID3=258
ParamStr3=

Name4=融券卖出
Type4=CLOUDDIY
FeatureID4=259
ParamStr4=

Name5=批量回购
Type5=CLOUDDIY
FeatureID5=262
ParamStr5=

HasLeftZHArea=1

[Panel_Multi_OT]
JyPanelNum=3

Name1=帐号
Type1=CLOUDDIY
FeatureID1=255

Name2=查询1
Type2=CLOUDDIY
FeatureID2=260

Name3=查询2
Type3=JYZDDATA
FeatureID3=gg_jycx_dzh

[HotKey]
HotKeyPadCode=CYYDX,CDSQD,CYEZQ,GPKCWT,CWGJY,GPMM,GPMMXY,MJYCX,CGS,GPGZHG,XYRZ,XYRQ,XYCX,GPCX,CTWAP,CVWAP,CYMD,CICB,CCL,CZCD,GPCX

Num=12
key1=w,资金股份
Key2=e,持仓明细

Key3=r,当日成交
Key4=t,可撤委托
Key5=y,当日委托
Key6=u,批次委托

Key7=z,可撤委托,1003
Key8=x,可撤委托,1004
Key9=c,可撤委托,1005
Key10=b,可撤委托,1007
Key11=m,锁定不撤,1009
Key12=n,锁定不撤,1008

[Total]
Num=25
PadCode1=GPMM
PadCode2=GPXGSG
PadCode3=GPCX
PadCode4=GPGZHG
PadCode5=GPMMXY
PadCode6=XYRZ
PadCode7=XYRQ
PadCode8=XYCX

PadCode9=CYMD
PadCode10=CZCD

PadCode11=CGS
PadCode12=CWGJY
PadCode13=CDSSH
PadCode14=CTWAP
PadCode15=CVWAP
PadCode16=CICB
PadCode17=CCL

PadCode18=MJYCX

PadCode19=GPYZZZ
PadCode20=GPKCWT

PadCode21=CDSQD
PadCode22=CYEZQ
PadCode23=CDBMR
PadCode24=CYYDX