; start strategy tester
TestExpert=Probe\MT4Probe_Volty
TestExpertParameters=
TestSymbol=EURUSD
TestPeriod=H1
TestModel=0
TestOptimization=false
TestDateEnable=true
TestFromDate=2025.01.01
TestToDate=2025.01.15
TestReplaceReport=true
TestReport=tester\files\mt4probe_volty
TestShutdownTerminal=true
