; common settings
EnableNews=false
Login=31383734
Server=ICMarketsSC-Demo03

; experts settings
ExpertsEnable=true
ExpertsDllImport=true
ExpertsExpImport=true
ExpertsTrades=false

; start strategy tester
TestExpert=Probe\MT4Probe_Volty
TestExpertParameters=MT4Probe_Volty.ini
TestSymbol=EURUSD
TestPeriod=H4
TestModel=2
TestOptimization=false
TestDateEnable=true
TestFromDate=2025.01.01
TestToDate=2025.01.15
TestVisualEnable=false
TestReplaceReport=true
TestReport=tester\files\mt4probe_volty_portable
TestShutdownTerminal=true
